### ISSUE TITLE
Chapter 8 - 01_dqn_basic.py

### ISSUE THREAD

**Issue by msfallah** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition#47]
When I run the code, I get the below errors 

Traceback (most recent call last):
  File "/Desktop/9781838826994_Code/Chapter08/01_dqn_basic.py", line 26, in <module>
    env = gym.make(params.env_name)
  File "/opt/anaconda3/envs/pytorch-env/lib/python3.9/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/opt/anaconda3/envs/pytorch-env/lib/python3.9/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/opt/anaconda3/envs/pytorch-env/lib/python3.9/site-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
  File "/opt/anaconda3/envs/pytorch-env/lib/python3.9/site-packages/gym/envs/atari/atari_env.py", line 49, in __init__
    self.game_path = atari_py.get_game_path(game)
  File "/opt/anaconda3/envs/pytorch-env/lib/python3.9/site-packages/atari_py/games.py", line 20, in get_game_path
    raise Exception('ROM is missing for %s, see https://github.com/openai/atari-py#roms for instructions' % (game_name,))
Exception: ROM is missing for pong, see https://github.com/openai/atari-py#roms for instructions

how to solve the issue?

**Comment by Shmuma** [comment]
Hi! Which version of ignite do you have? To make code work, you have to have versions which are noted in the `requirements.txt`

**Comment by Lynnehao** [comment]
When I run the code, I get the below errors,want can i  do 
Traceback (most recent call last):
  File "/content/drive/MyDrive/Hands_on_DRL/Deep-Reinforcement-Learning-Hands-On-Second-Edition/Chapter08/01_dqn_basic.py", line 62, in <module>
    common.setup_ignite(engine, params, exp_source, NAME)
  File "/content/drive/MyDrive/Hands_on_DRL/Deep-Reinforcement-Learning-Hands-On-Second-Edition/Chapter08/lib/common.py", line 158, in setup_ignite
    handler.attach(engine)
  File "/usr/local/lib/python3.7/dist-packages/ptan/ignite.py", line 35, in attach
    engine.register_events(*EpisodeEvents)
  File "/usr/local/lib/python3.7/dist-packages/ignite/engine/engine.py", line 222, in register_events
    raise TypeError(f"Value at {index} of event_names should be a str or EventEnum, but given {e}")
TypeError: Value at 0 of event_names should be a str or EventEnum, but given EpisodeEvents.EPISODE_COMPLETED

**Comment by Shmuma** [comment]
Hi! Something is wrong with your versions, especially ignite. Please check
