### ISSUE TITLE
Problem with ":" in file names on Windows machine in common.py

### ISSUE THREAD

**Issue by Petzy68** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition#62]
When running Chapter10 I get an error as seen below. It is because Windows don't like ":" in file names.

row 89 in common.py uses: datetime.now().isoformat(timespec='minutes')
and it returns: '2022-10-20T11:16'

I changed that line to this and it works: datetime.now().isoformat(timespec='minutes').replace(':', '')
It would be nice if it could be changed in the original code. (Or something else if there is a better way)

Regards,
Peter

Reading data\YNDX_160101_161231.csv
Read done, got 131542 rows, 99752 filtered, 0 open prices adjusted
Reading data\YNDX_150101_151231.csv
Read done, got 130566 rows, 104412 filtered, 0 open prices adjusted
Traceback (most recent call last):

  File "C:\Anaconda3\envs\rlbook\lib\site-packages\tensorboardX\record_writer.py", line 47, in directory_check
    factory = REGISTERED_FACTORIES[prefix]

KeyError: 'runs/2022-10-20T11'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Anaconda3\envs\rlbook\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\onedrive - it-resultat sverige ab\strategy development\_rlbook\deep-reinforcement-learning-hands-on-second-edition\chapter10\train_model.py", line 109, in <module>
    extra_metrics=('values_mean',))

  File "C:\OneDrive - IT-Resultat Sverige AB\Strategy Development\_rlbook\Deep-Reinforcement-Learning-Hands-On-Second-Edition\Chapter10\lib\common.py", line 91, in setup_ignite
    tb = tb_logger.TensorboardLogger(log_dir=logdir)

  File "C:\Anaconda3\envs\rlbook\lib\site-packages\ignite\contrib\handlers\tensorboard_logger.py", line 161, in __init__
    self.writer = SummaryWriter(*args, **kwargs)

  File "C:\Anaconda3\envs\rlbook\lib\site-packages\tensorboardX\writer.py", line 301, in __init__
    self._get_file_writer()

  File "C:\Anaconda3\envs\rlbook\lib\site-packages\tensorboardX\writer.py", line 353, in _get_file_writer
    **self.kwargs)

  File "C:\Anaconda3\envs\rlbook\lib\site-packages\tensorboardX\writer.py", line 106, in __init__
    logdir, max_queue, flush_secs, filename_suffix)

  File "C:\Anaconda3\envs\rlbook\lib\site-packages\tensorboardX\event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)

  File "C:\Anaconda3\envs\rlbook\lib\site-packages\tensorboardX\record_writer.py", line 51, in directory_check
    os.makedirs(path)

  File "C:\Anaconda3\envs\rlbook\lib\os.py", line 223, in makedirs
    mkdir(name, mode)

NotADirectoryError: [WinError 267] Katalognamnet är felaktigt: 'runs/2022-10-20T11:11-simple-RUN'
(Translated from Swedish to English above row is:
NotADirectoryError: [WinError 267] Folder name is wrong: 'runs/2022-10-20T11:11-simple-RUN'

**Comment by WhizZest** [comment]
I also encountered the same problem, in Chapter 9, it can be solved with ```replace(':', '-')```.
